
import static com.sun.java.accessibility.util.GUIInitializedMulticaster.remove;
import static java.awt.AWTEventMulticaster.remove;
import java.awt.Color;
import static java.awt.JobAttributes.DestinationType.FILE;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;
import java.awt.print.PrinterException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringReader;
import static java.nio.file.Files.lines;
import java.util.ArrayList;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.io.*;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Document;
import javax.swing.text.Element;
import javax.swing.text.Highlighter;
import javax.swing.text.JTextComponent;
import static sun.nio.ch.IOStatus.EOF;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Daniel Mobatsion -----------5550
 *          Duressa Agaro -------------5574
 */
public class Main extends javax.swing.JFrame {
private JFileChooser fc=new JFileChooser();
    /**
     * Creates new form Main
     */

String s[][] = new String [3][3];
       String space = " ";
       Clipboard clipboard = getToolkit().getSystemClipboard();
    public Main() {
        initComponents();
        jLabel_result.setVisible(false);
        //Main ee = new Main();
        //ee.setExtendedState(JFrame.MAXIMIZED_BOTH);
        //ee.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton3 = new javax.swing.JButton();
        jToolBar3 = new javax.swing.JToolBar();
        jButton7 = new javax.swing.JButton();
        jToolBar8 = new javax.swing.JToolBar();
        jButton2 = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        jButton5 = new javax.swing.JButton();
        jToolBar4 = new javax.swing.JToolBar();
        jButton13 = new javax.swing.JButton();
        jToolBar5 = new javax.swing.JToolBar();
        jButton12 = new javax.swing.JButton();
        jToolBar13 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jToolBar6 = new javax.swing.JToolBar();
        jButton6 = new javax.swing.JButton();
        jToolBar7 = new javax.swing.JToolBar();
        jButton4 = new javax.swing.JButton();
        jToolBar11 = new javax.swing.JToolBar();
        jToolBar12 = new javax.swing.JToolBar();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jProgressBar2 = new javax.swing.JProgressBar();
        jToolBar10 = new javax.swing.JToolBar();
        jLabel2 = new javax.swing.JLabel();
        jToolBar9 = new javax.swing.JToolBar();
        jToolBar14 = new javax.swing.JToolBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        out = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        statusk = new javax.swing.JLabel();
        jLabel_result = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        check = new javax.swing.JTextArea();
        searchfield = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenuItem6.setText("jMenuItem6");

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("D&D Query Processing");
        setLocation(new java.awt.Point(0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jToolBar1.setBackground(new java.awt.Color(153, 204, 255));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Capture3.PNG"))); // NOI18N
        jButton3.setText("New");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jToolBar3.setRollover(true);
        jToolBar1.add(jToolBar3);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Captureopen.PNG"))); // NOI18N
        jButton7.setText("Open");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton7);

        jToolBar8.setRollover(true);
        jToolBar1.add(jToolBar8);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Capture2.PNG"))); // NOI18N
        jButton2.setText("Save");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jToolBar2.setRollover(true);
        jToolBar1.add(jToolBar2);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Capturecut.PNG"))); // NOI18N
        jButton5.setText("Cut");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jToolBar1.add(jButton5);

        jToolBar4.setRollover(true);
        jToolBar1.add(jToolBar4);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Captureredo.PNG"))); // NOI18N
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.setFocusable(false);
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton13);

        jToolBar5.setRollover(true);
        jToolBar1.add(jToolBar5);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Capture4.PNG"))); // NOI18N
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.setFocusable(false);
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton12);

        jToolBar13.setRollover(true);
        jToolBar1.add(jToolBar13);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/capture1.PNG"))); // NOI18N
        jButton1.setText("Run");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButton1KeyTyped(evt);
            }
        });
        jToolBar1.add(jButton1);

        jToolBar6.setRollover(true);
        jToolBar1.add(jToolBar6);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Capturecompile.PNG"))); // NOI18N
        jButton6.setText("Compile");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton6);

        jToolBar7.setRollover(true);
        jToolBar1.add(jToolBar7);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Capturedebug.PNG"))); // NOI18N
        jButton4.setText("Debug");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToolBar1.add(jButton4);

        jToolBar11.setRollover(true);
        jToolBar1.add(jToolBar11);

        jToolBar12.setRollover(true);
        jToolBar1.add(jToolBar12);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.addTab("Source", jProgressBar2);

        jToolBar10.setFloatable(false);
        jToolBar10.setRollover(true);

        jLabel2.setText("Normal Text File");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToolBar10, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jToolBar9.setFloatable(false);
        jToolBar9.setRollover(true);

        jToolBar14.setRollover(true);

        txtarea.setColumns(20);
        txtarea.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        txtarea.setForeground(new java.awt.Color(0, 0, 51));
        txtarea.setRows(5);
        txtarea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtareaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtareaKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtarea);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        out.setEditable(false);
        out.setBackground(new java.awt.Color(204, 204, 204));
        out.setColumns(20);
        out.setRows(5);
        out.setText(" No");
        out.setAutoscrolls(false);
        out.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        out.setEnabled(false);
        out.setFocusable(false);
        jScrollPane2.setViewportView(out);

        jLabel1.setText("Execute Time :00:00:00 ");

        jLabel_result.setForeground(new java.awt.Color(0, 102, 0));
        jLabel_result.setText("Create Database Successfully");

        check.setEditable(false);
        check.setBackground(new java.awt.Color(204, 204, 204));
        check.setColumns(20);
        check.setRows(5);
        jScrollPane3.setViewportView(check);

        searchfield.setForeground(new java.awt.Color(0, 0, 51));

        jButton8.setText("Search");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Capture1_2.PNG"))); // NOI18N
        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Capture8.PNG"))); // NOI18N
        jMenuItem1.setText("New");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Capture3_1.PNG"))); // NOI18N
        jMenuItem2.setText("Open");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Capture4_1.PNG"))); // NOI18N
        jMenuItem3.setText("Save");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Capture2.PNG"))); // NOI18N
        jMenuItem4.setText("SaveAs");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Capture5.PNG"))); // NOI18N
        jMenuItem5.setText("Import");
        jMenu1.add(jMenuItem5);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Capture6.PNG"))); // NOI18N
        jMenuItem8.setText("Export");
        jMenu1.add(jMenuItem8);

        jMenuItem17.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Print_30px.png"))); // NOI18N
        jMenuItem17.setText("Print");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem17);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Capture2_2.PNG"))); // NOI18N
        jMenuItem9.setText("Exit");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Capture2532.PNG"))); // NOI18N
        jMenu2.setText("Edit");

        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Capturecccopyyy.PNG"))); // NOI18N
        jMenuItem13.setText("Copy");
        jMenuItem13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem13MouseClicked(evt);
            }
        });
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem13);

        jMenuItem15.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Capturepasteee.PNG"))); // NOI18N
        jMenuItem15.setText("Paste");
        jMenuItem15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem15MouseClicked(evt);
            }
        });
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem15);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Capturevvvvv.PNG"))); // NOI18N
        jMenu3.setText("View");
        jMenuBar1.add(jMenu3);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Capturerrrrr.PNG"))); // NOI18N
        jMenu7.setText("Run");

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/capture1.PNG"))); // NOI18N
        jMenuItem11.setText("Run ");
        jMenu7.add(jMenuItem11);

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Captureint.PNG"))); // NOI18N
        jMenuItem14.setText("Launch in InternetExplorer");
        jMenu7.add(jMenuItem14);

        jMenuBar1.add(jMenu7);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Capturecccc.PNG"))); // NOI18N
        jMenu6.setText("Compile");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Capturehhhhh.PNG"))); // NOI18N
        jMenu8.setText("Help");

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Capture11.PNG"))); // NOI18N
        jMenuItem10.setText("About ");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem10);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Capture256.PNG"))); // NOI18N
        jMenuItem12.setText("Help");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem12);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(907, 907, 907)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_result, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(202, 202, 202)
                                        .addComponent(jToolBar9, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(176, 176, 176)
                                        .addComponent(statusk, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 1017, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchfield, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchfield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jToolBar14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE))
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_result)
                            .addComponent(statusk, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addGap(23, 23, 23)
                        .addComponent(jToolBar9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void openFile(String fileName){
FileReader fr = null;
try{
	fr=new FileReader(fileName);
	txtarea.read(fr,null);
	fr.close();
	setTitle(fileName);
	
}catch(IOException e){
	e.printStackTrace();
}
}
public void createdatabase(){
//       String create[][] = new String [3][3];
//       create[0][0]="create";
//       String space =" ";
//       String database[][] = new String [1][1];
//       database[0][0]="database";
//       String databasename[]= new String [100];
//       databasename[0] =txtarea.getText().concat(";");
//       
//       String databasecreate =create[0][0].concat(space).concat(database[0][0]).concat(space).concat(databasename[0]);
//     // String databasecreate1 =create[0][0]+space+database[0][0]+space+databasename[0];
       if(txtarea.getText().equals("create database [a-zA-Z]")){
           jLabel_result.setVisible(true);
       }
       else {
           jLabel_result.setText("Unsucessfull built");
           jLabel_result.setForeground(Color.red);
       }
       
   }
public void saveas(){
	if(fc.showSaveDialog(null)== JFileChooser.APPROVE_OPTION){
		FileWriter fw = null;
		try{
			fw=new FileWriter(fc.getSelectedFile().getAbsolutePath());
			txtarea.write(fw);
			fw.close();
	}catch (IOException e){
		e.printStackTrace();
	}
	}
}
private void save() {
        PrintWriter fout = null;
        try{
            fout= new PrintWriter(new FileWriter("test.txt"));
            String s=txtarea.getText();
            StringTokenizer st=new StringTokenizer(s,System.getProperty("line.separator")); 
            while (st.hasMoreElements()) {
                fout.println(st.nextToken());

            }
         JOptionPane.showMessageDialog(rootPane,"File saved");
        } catch(IOException e){
            
        }finally{
            fout.close();
        }
}
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       Main dd = new Main();
    
       dd.setExtendedState(JFrame.MAXIMIZED_BOTH);
       dd.setVisible(true);
       dd.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
           Main dd = new Main();
       this.dispose();
       dd.setExtendedState(JFrame.MAXIMIZED_BOTH);
       dd.setVisible(true);
       dd.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
            if(fc.showOpenDialog(null)==JFileChooser.APPROVE_OPTION)
   {
    		openFile(fc.getSelectedFile().getAbsolutePath());
    	
          }  
   
   
    //ImageIcon icon = new ImageIcon(filename);
    //txtarea.setIcon(icon);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
         if(fc.showOpenDialog(null)==JFileChooser.APPROVE_OPTION)
   {
    		openFile(fc.getSelectedFile().getAbsolutePath());
    	
          }     
       
   
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
       
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
       About ab = new About();
       ab.setVisible(true);
       ab.setLocation(300, 200);
       
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
      StringReader sr = new StringReader(txtarea.getText());
       BufferedReader br = new BufferedReader(sr);
       String nextLine ;
       ArrayList<String> line = new ArrayList<>();
       
       try {
           while((nextLine = br.readLine()) !=null){
               line.add(nextLine);
               Identifier_check hh = new Identifier_check(nextLine);
              // Tokenization_class tok=new Tokenization_class(nextLine);
           }
         
       }catch(IOException ex)
       {
           Logger.getLogger(Main.class.getName()).log(Level.SEVERE,null, ex);
       }
       for (String sline:line){
          //JOptionPane.showMessageDialog(null, sline);
         //tonkizing_line_statement_to_word obj = new tonkizing_line_statement_to_word(sline);
  
    
//    
//          try {
//            //  hh.Identifier_check(sline, NORMAL);
//              obj.token(sline);
//                //PassToken tok = new PassToken();
//          } catch (IOException ex) {
//              Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
//          }
//    
//createdatabase();
      //   table tb = new table();
        //   tb.setVisible(true);
        
       } 
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       
         if(txtarea.getText().equals("")){
           saveas(); 
        }
         else
         {
             save();
         }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        if(txtarea.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please Write Some thing on Your Textarea!");
        }
        else{
           saveas(); 
        }
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void txtareaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtareaKeyTyped
        
      //  if(txtarea.getText().equals("")){
           // txtarea.getText();
      int linecount=0;
        int word_count=0;
        int charactercount=0;
        int cursor_position=txtarea.getCaretPosition();
        String c =" " + cursor_position;
        String lineReader;
        StringReader sr = new StringReader(txtarea.getText());
        BufferedReader br = new BufferedReader(sr);
        
        try {
            while((lineReader=br.readLine())!=null)
            {
            linecount++;
            for (int i=0;i<lineReader.length();i++)
            {
                char found = lineReader.charAt(i);
                if (found==' ')
                {
                word_count++;      
                 }
                else if(found!=' '){
                    charactercount++;
                }
               
            }
            }
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } 
        statusk.setText("Line:  "+ linecount +"       "+"Wordcount :    "+" "+ word_count +"          "+ "Cursor_position :" + c+ "      "+ "Character  "+ charactercount);
      int caretPosition = txtarea.getDocument().getLength();
        Element root = txtarea.getDocument().getDefaultRootElement();
        StringBuilder lineNumbersTextBuilder = new StringBuilder();
        lineNumbersTextBuilder.append("1").append(System.lineSeparator());

        for (int j = 2; j< root.getElementIndex(caretPosition) + 1; j++)
        {
            lineNumbersTextBuilder.append(j).append(System.lineSeparator());
        }
out.setText("\n"+lineNumbersTextBuilder);
out.setAutoscrolls(false);
    }//GEN-LAST:event_txtareaKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       save();
           
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyTyped
       
    }//GEN-LAST:event_jButton1KeyTyped

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed
//    try { 
//        Identifier_check ic =new   Identifier_check(txtarea.getText());
//    } catch (IOException ex) {
//        Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
//    }
        
    }//GEN-LAST:event_jMenu6ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed

        try {
            boolean check =txtarea.print();
            if(check){
                JOptionPane.showMessageDialog(null,"Done");
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Processing");
            }

        } catch (PrinterException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void txtareaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtareaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtareaKeyPressed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
     String cutString = txtarea.getSelectedText();
     StringSelection cutSelection = new StringSelection(cutString);
     clipboard.setContents(cutSelection, cutSelection);
     txtarea.replaceRange("", txtarea.getSelectionStart(),txtarea.getSelectionEnd());
    }//GEN-LAST:event_jButton5MouseClicked

    private void jMenuItem15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem15MouseClicked
      try {
          Transferable pasteText =clipboard.getContents(Main.this);
          String sel =(String)pasteText.getTransferData(DataFlavor.stringFlavor);
        txtarea.replaceRange(sel,txtarea.getSelectionStart(),txtarea.getSelectionEnd());
        
        }
      catch(Exception e){
          System.out.println("Didnt work");
      }
    }//GEN-LAST:event_jMenuItem15MouseClicked

    private void jMenuItem13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem13MouseClicked
       String copyText = txtarea.getSelectedText();
       StringSelection copyselection = new StringSelection(copyText);
       clipboard.setContents(copyselection, copyselection);
    }//GEN-LAST:event_jMenuItem13MouseClicked

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
       String copyText = txtarea.getSelectedText();
       StringSelection copyselection = new StringSelection(copyText);
       clipboard.setContents(copyselection, copyselection);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        try {
          Transferable pasteText =clipboard.getContents(Main.this);
          String sel =(String)pasteText.getTransferData(DataFlavor.stringFlavor);
        txtarea.replaceRange(sel,txtarea.getSelectionStart(),txtarea.getSelectionEnd());
        
        }
      catch(Exception e){
          System.out.println("Didnt work");
      }
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       searchTextArea(txtarea, searchfield.getText());        
    }//GEN-LAST:event_jButton8ActionPerformed

  class myhighligher extends DefaultHighlighter.DefaultHighlightPainter{

        public myhighligher(Color c) {
            super(c);
        }     
  }
  DefaultHighlighter.HighlightPainter highlighter = new myhighligher(Color.yellow);
  public void removeHighLight(JTextComponent textComp){
      Highlighter removeHighlighter = textComp.getHighlighter();
      Highlighter.Highlight[] remove = removeHighlighter.getHighlights();
      for(int i=0; i<remove.length; i++){
          if(remove[i].getPainter() instanceof myhighligher){
          removeHighlighter.removeHighlight(remove[i]);
      }
          
      }
  }
  public void searchTextArea(JTextComponent textComp,String textString){
      removeHighLight(textComp);
      try{
          Highlighter hilight = textComp.getHighlighter();
          Document doc = textComp.getDocument();
          String text = doc.getText(0, doc.getLength());
          
          int pos =0;
          while((pos = text.toUpperCase().indexOf(textString.toUpperCase(),pos)) >=0){
              hilight.addHighlight(pos,pos+textString.length(), highlighter);
              pos+= textString.length();
          }
          
      }
      catch(Exception e){
          
      }
  }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea check;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel_result;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar10;
    private javax.swing.JToolBar jToolBar11;
    private javax.swing.JToolBar jToolBar12;
    private javax.swing.JToolBar jToolBar13;
    private javax.swing.JToolBar jToolBar14;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JToolBar jToolBar5;
    private javax.swing.JToolBar jToolBar6;
    private javax.swing.JToolBar jToolBar7;
    private javax.swing.JToolBar jToolBar8;
    private javax.swing.JToolBar jToolBar9;
    private javax.swing.JTextArea out;
    private javax.swing.JTextField searchfield;
    private javax.swing.JLabel statusk;
    public static javax.swing.JTextArea txtarea;
    // End of variables declaration//GEN-END:variables
}
